# Generated by Django 4.0.6 on 2022-07-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_phone_best_selling_alter_phone_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
    ]
