# Generated by Django 4.0.6 on 2022-08-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
        ('userprofile', '0003_cart_phone_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phone'),
        ),
    ]
